# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core_v2_pb2 as core__v2__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceV2Stub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TelemetrySession = channel.stream_stream(
                '/CdiTelemetryV2.TelemetryServiceV2/TelemetrySession',
                request_serializer=core__v2__pb2.DeviceToManager.SerializeToString,
                response_deserializer=core__v2__pb2.ManagerToDevice.FromString,
                _registered_method=True)


class TelemetryServiceV2Servicer:
    """Missing associated documentation comment in .proto file."""

    def TelemetrySession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TelemetrySession': grpc.stream_stream_rpc_method_handler(
                    servicer.TelemetrySession,
                    request_deserializer=core__v2__pb2.DeviceToManager.FromString,
                    response_serializer=core__v2__pb2.ManagerToDevice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CdiTelemetryV2.TelemetryServiceV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CdiTelemetryV2.TelemetryServiceV2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryServiceV2:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TelemetrySession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/CdiTelemetryV2.TelemetryServiceV2/TelemetrySession',
            core__v2__pb2.DeviceToManager.SerializeToString,
            core__v2__pb2.ManagerToDevice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
